export default Object.freeze({
  TRANSACTIONS_ADD: 'TransactionsAll/TRANSACTIONS_ADD',

  FETCHING_LATEST_TRANSACTION: 'TransactionsAll/FETCHING_LATEST_TRANSACTION',
  FETCHING_LATEST_TRANSACTION_SUCCESS: 'TransactionsAll/FETCHING_LATEST_TRANSACTION_SUCCESS',
  FETCHING_LATEST_TRANSACTION_FAILURE: 'TransactionsAll/FETCHING_LATEST_TRANSACTION_FAILURE',

  FETCHING_LATEST_VALIDATOR: 'TransactionsAll/FETCHING_LATEST_VALIDATOR',
  FETCHING_LATEST_VALIDATOR_SUCCESS: 'TransactionsAll/FETCHING_LATEST_VALIDATOR_SUCCESS',
  FETCHING_LATEST_VALIDATOR_FAILURE: 'TransactionsAll/FETCHING_LATEST_VALIDATOR_FAILURE',

  FETCHING_STAKING_VALIDATOR: 'TransactionsAll/FETCHING_STAKING_VALIDATOR',
  FETCHING_STAKING_VALIDATOR_SUCCESS: 'TransactionsAll/FETCHING_STAKING_VALIDATOR_SUCCESS',
  FETCHING_STAKING_VALIDATOR_FAILURE: 'TransactionsAll/FETCHING_STAKING_VALIDATOR_FAILURE',

  FETCHING_TX_CHART: 'TransactionsAll/FETCHING_TX_CHART',
  FETCHING_TX_CHART_SUCCESS: 'TransactionsAll/FETCHING_TX_CHART_SUCCESS',
  FETCHING_TX_CHART_FAILURE: 'TransactionsAll/FETCHING_TX_CHART_FAILURE',

  FETCHING_TX_DETAIL: 'TransactionsAll/FETCHING_TX_DETAIL',
  FETCHING_TX_DETAIL_SUCCESS: 'TransactionsAll/FETCHING_TX_DETAIL_SUCCESS',
  FETCHING_TX_DETAIL_FAILURE: 'TransactionsAll/FETCHING_TX_DETAIL_FAILURE',

  FETCHING_LATEST_BLOCK: 'Blocks/FETCHING_LATEST_BLOCK',
  FETCHING_LATEST_BLOCK_SUCCESS: 'Blocks/FETCHING_LATEST_BLOCK_SUCCESS',
  FETCHING_LATEST_BLOCK_FAILURE: 'Blocks/FETCHING_LATEST_BLOCK_FAILURE',

  FETCHING_NEWEST_BLOCK: 'Blocks/FETCHING_NEWEST_BLOCK',
  FETCHING_NEWEST_BLOCK_SUCCESS: 'Blocks/FETCHING_NEWEST_BLOCK_SUCCESS',
  FETCHING_NEWEST_BLOCK_FAILURE: 'Blocks/FETCHING_NEWEST_BLOCK_FAILURE',
});
