export default Object.freeze({
  FETCHING_LATEST_BLOCK: 'FETCHING_LATEST_BLOCK',
  FETCHING_LATEST_BLOCK_SUCCESS: 'FETCHING_LATEST_BLOCK_SUCCESS',
  FETCHING_LATEST_BLOCK_FAILURE: 'FETCHING_LATEST_BLOCK_FAILURE',
});
